#!/bin/sh

dir="$(dirname "$(readlink -f "$0")")"
token="$("${dir}/login")"

curl -sSfL \
  -H 'GData-Version: 3.0' \
  -H 'Authorization: Bearer '"$token" \
  'https://www.google.com/m8/feeds/contacts/default/full?max-results=100000'
