#!/bin/sh

dir="$(dirname "$(readlink -f "$0")")"
token="$("${dir}/login")" || exit 1

curl -sSfL \
  -H 'GData-Version: 3.0' \
  -H 'Authorization: Bearer '"$token" \
  'https://www.google.com/m8/feeds/contacts/default/full?max-results=100000' \
  -o "${dir}/all.xml.tmp" && mv "${dir}/all.xml.tmp" "${dir}/all.xml"
